services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.rails
    ports:
      - "3002:3000"  # Rails API port
    depends_on:
      - db
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - bundler_gems:/usr/local/bundle  # Cache gems between builds
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Give more time for initial setup

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  bundler_gems:  # Volume for caching gems 